source              : .
destination         : ./_site
theme               : minima

title: "The Gauntlet of Chaos"

header_pages:
  - README.md
  - TODO.md
  - MODS.md

minima:
  skin: auto