name = "Gauntlet of Chaos"
author = "MaverickMartyn"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c9f3a58e60dbf7970e271c6735a43ff736fe1fc38a87bb9d82bd1e19a99fb929"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
