name = "The Gauntlet of Chaos"
author = "MaverickMartyn"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5e3e4c089996d5cc65a0d1cd79ca02ae5ade1bc3c0a739129daeb3b88178c7a4"

[versions]
forge = "40.2.10"
minecraft = "1.18.2"
