name = "Gauntlet of Chaos"
author = "MaverickMartyn"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8381263742384403636c39e9c4cf907fbb1b5c88f38be1a0c33d51df99bef440"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
