name = "Gauntlet of Chaos"
author = "MaverickMartyn"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "379a680b24a5ac9c41e5f90f529ae2bb40540893b7f2fbbb99301dd424b62ae1"

[versions]
forge = "40.2.10"
minecraft = "1.18.2"
