name = "Gauntlet of Chaos"
author = "MaverickMartyn"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d83164b94d817696f910707d40c6a723a73574668e64c24ff9afc5f0dc1cd3f"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
