name = "Gauntlet of Chaos"
author = "MaverickMartyn"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5f23103829135a685ad655b1fff94762a33c0391557f0a7156cfa5e9cdb7a888"

[versions]
forge = "40.2.10"
minecraft = "1.18.2"
