name = "The Gauntlet of Chaos"
author = "MaverickMartyn"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "990abc772df16d728424bb1a4e98ad9241e0fd00cba641bd3485e72046561ae5"

[versions]
forge = "40.2.10"
minecraft = "1.18.2"
